// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

import {Test} from "forge-std/Test.sol";
import {JobVault} from "../src/JobVault.sol";
import {JobVaultHarness} from "./harness/JobVaultHarness.sol";
import {MockUSDC} from "./mocks/MockUSDC.sol";

/// @notice Replays the off-chain policy vectors (packages/policy) against JobVault. Each case must
///         produce the same outcome on-chain as in the TypeScript policy engine. The fixture is
///         generated by the export:parity script in packages/policy, and a TypeScript test fails
///         if it's stale.
contract PolicyParityTest is Test {
    bytes32 internal constant JOB = keccak256("parity");
    address internal owner = makeAddr("owner");
    address internal operator = makeAddr("operator");
    address internal payee = makeAddr("payee");

    /// @dev Fixed start time. Reading block.timestamp right after vm.warp can return a stale value.
    uint64 internal constant T0 = 1_790_000_000;

    string internal fixture;

    function setUp() public {
        fixture = vm.readFile(string.concat(vm.projectRoot(), "/test/fixtures/policy-parity.json"));
    }

    function test_everyVectorMatchesTheContract() public {
        uint256 count = vm.parseJsonUint(fixture, ".count");
        assertGt(count, 0, "empty fixture");
        for (uint256 i; i < count; ++i) {
            _runCase(i);
        }
    }

    function _runCase(uint256 i) internal {
        string memory p = string.concat(".cases[", vm.toString(i), "]");
        string memory name = vm.parseJsonString(fixture, string.concat(p, ".name"));
        string memory expected = vm.parseJsonString(fixture, string.concat(p, ".expect"));
        uint256 snapshot = vm.snapshotState();

        vm.warp(T0);
        MockUSDC usdc = new MockUSDC();
        JobVaultHarness vault = new JobVaultHarness(usdc, operator);
        _openJob(vault, usdc, p);

        uint128 amount = uint128(vm.parseJsonUint(fixture, string.concat(p, ".amount")));
        uint64 version = vault.getJob(JOB).policyVersion;
        JobVault.Approval memory none = JobVault.Approval({approver: address(0), deadline: 0, signature: ""});
        vm.prank(operator);
        (bool ok, bytes memory ret) =
            address(vault).call(abi.encodeCall(JobVault.release, (JOB, bytes32(i + 1), payee, amount, version, none)));

        if (_eq(expected, "ALLOWED")) {
            assertTrue(ok, name);
        } else {
            assertFalse(ok, name);
            assertEq(bytes4(ret), _selectorFor(expected), name);
        }
        vm.revertToState(snapshot);
    }

    function _openJob(JobVaultHarness vault, MockUSDC usdc, string memory p) internal {
        uint128 budget = uint128(vm.parseJsonUint(fixture, string.concat(p, ".budget")));
        uint128 deposited = uint128(vm.parseJsonUint(fixture, string.concat(p, ".deposited")));
        uint128 perTxCap = uint128(vm.parseJsonUint(fixture, string.concat(p, ".perTxCap")));
        JobVault.JobParams memory params = JobVault.JobParams({
            agentWallet: makeAddr("agentWallet"),
            budget: budget,
            perTxCap: perTxCap,
            approvalThreshold: uint128(vm.parseJsonUint(fixture, string.concat(p, ".approvalThreshold"))),
            windowCap: uint128(vm.parseJsonUint(fixture, string.concat(p, ".windowCap"))),
            window: uint64(vm.parseJsonUint(fixture, string.concat(p, ".windowSeconds"))),
            expiry: T0 + 1 days
        });

        usdc.mint(owner, deposited);
        vm.startPrank(owner);
        usdc.approve(address(vault), deposited);
        vault.createJob(JOB, params);
        vault.fund(JOB, deposited);
        if (vm.parseJsonBool(fixture, string.concat(p, ".payeeAllowed"))) vault.setPayee(JOB, payee, true);
        vm.stopPrank();

        uint64 windowAge = uint64(vm.parseJsonUint(fixture, string.concat(p, ".windowAge")));
        vault.forceState(
            JOB,
            _status(vm.parseJsonString(fixture, string.concat(p, ".status"))),
            uint128(vm.parseJsonUint(fixture, string.concat(p, ".spent"))),
            T0 - windowAge,
            uint128(vm.parseJsonUint(fixture, string.concat(p, ".windowSpent")))
        );
        if (vm.parseJsonBool(fixture, string.concat(p, ".expired"))) vm.warp(params.expiry);
    }

    function _status(string memory s) internal pure returns (JobVault.Status) {
        if (_eq(s, "ACTIVE")) return JobVault.Status.Active;
        if (_eq(s, "PAUSED")) return JobVault.Status.Paused;
        if (_eq(s, "CLOSED")) return JobVault.Status.Closed;
        return JobVault.Status.None; // DRAFT and PENDING_CHAIN: not live on-chain yet
    }

    function _selectorFor(string memory reason) internal pure returns (bytes4) {
        if (_eq(reason, "JOB_NOT_ACTIVE")) return JobVault.JobNotActive.selector;
        if (_eq(reason, "JOB_EXPIRED")) return JobVault.JobExpired.selector;
        if (_eq(reason, "INVALID_AMOUNT")) return JobVault.ZeroAmount.selector;
        if (_eq(reason, "PAYEE_NOT_ALLOWED")) return JobVault.PayeeNotAllowed.selector;
        if (_eq(reason, "PER_TX_CAP_EXCEEDED")) return JobVault.PerTxCapExceeded.selector;
        if (_eq(reason, "JOB_BUDGET_EXCEEDED")) return JobVault.BudgetExceeded.selector;
        if (_eq(reason, "JOB_UNDERFUNDED")) return JobVault.Underfunded.selector;
        if (_eq(reason, "RATE_LIMITED")) return JobVault.RateLimited.selector;
        if (_eq(reason, "NEEDS_APPROVAL")) return JobVault.ApprovalRequired.selector;
        revert(string.concat("no contract error mapped for ", reason));
    }

    function _eq(string memory a, string memory b) internal pure returns (bool) {
        return keccak256(bytes(a)) == keccak256(bytes(b));
    }
}
